export const UPDATE_PRODUCTS_FILTER_FIELD = 'UPDATE_PRODUCTS_FILTER_FIELD';
export const UPDATE_PRODUCTS_FILTER_CATEGORIES = 'UPDATE_PRODUCTS_FILTER_CATEGORIES';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';

