export const UPDATE_PAGINATION_CURRENT_PAGE =
  'app/pagination/UPDATE_PAGINATION_CURRENT_PAGE';

export const SHIFT_PAGINATION_PAGE_BOUNDS_FORWARD =
  'app/pagination/SHIFT_PAGINATION_PAGE_BOUNDS_FORWARD';

export const SHIFT_PAGINATION_PAGE_BOUNDS_BACK =
  'app/pagination/SHIFT_PAGINATION_PAGE_BOUNDS_BACK';
