export const UPDATE_PAGINATION_CURRENT_PAGE =
  'app/pagination/UPDATE_PAGINATION_CURRENT_PAGE';
export const MAKE_PAGINATION_CONTROLS_ACTIVE =
  'app/pagination/MAKE_PAGINATION_CONTROLS_ACTIVE';
export const MAKE_PAGINATION_CONTROLS_INACTIVE =
  'app/pagination/MAKE_PAGINATION_CONTROLS_INACTIVE';
export const MAKE_PAGINATION_CONTROL_PREV_ACTIVE =
  'app/pagination/MAKE_PAGINATION_CONTROL_PREV_ACTIVE';
export const MAKE_PAGINATION_CONTROL_PREV_INACTIVE =
  'app/pagination/MAKE_PAGINATION_CONTROL_PREV_INACTIVE';
export const MAKE_PAGINATION_CONTROL_NEXT_ACTIVE =
  'app/pagination/MAKE_PAGINATION_CONTROL_NEXT_ACTIVE';
export const MAKE_PAGINATION_CONTROL_NEXT_INACTIVE =
  'app/pagination/MAKE_PAGINATION_CONTROL_NEXT_INACTIVE';
export const SHIFT_PAGINATION_PAGE_BOUNDS_FORWARD =
  'app/pagination/SHIFT_PAGINATION_PAGE_BOUNDS_FORWARD';
export const SHIFT_PAGINATION_PAGE_BOUNDS_BACK =
  'app/pagination/SHIFT_PAGINATION_PAGE_BOUNDS_BACK';
