export const SET_INITIAL_STATE = 'app/products/SET_INITIAL_STATE';
export const UPDATE_PRODUCTS_FILTER_FIELD =
  'app/products/UPDATE_PRODUCTS_FILTER_FIELD';
export const UPDATE_PRODUCTS_FILTER_CATEGORIES =
  'app/products/UPDATE_PRODUCTS_FILTER_CATEGORIES';
export const UPDATE_PAGINATION_CURRENT_PAGE =
  'app/products/UPDATE_PAGINATION_CURRENT_PAGE';
export const MAKE_PAGINATION_CONTROLS_ACTIVE =
  'app/products/MAKE_PAGINATION_CONTROLS_ACTIVE';
export const MAKE_PAGINATION_CONTROLS_INACTIVE =
  'app/products/MAKE_PAGINATION_CONTROLS_INACTIVE';
export const MAKE_PAGINATION_CONTROL_PREV_ACTIVE =
  'app/products/MAKE_PAGINATION_CONTROL_PREV_ACTIVE';
export const MAKE_PAGINATION_CONTROL_PREV_INACTIVE =
  'app/products/MAKE_PAGINATION_CONTROL_PREV_INACTIVE';
export const MAKE_PAGINATION_CONTROL_NEXT_ACTIVE =
  'app/products/MAKE_PAGINATION_CONTROL_NEXT_ACTIVE';
export const MAKE_PAGINATION_CONTROL_NEXT_INACTIVE =
  'app/products/MAKE_PAGINATION_CONTROL_NEXT_INACTIVE';
export const SHIFT_PAGINATION_PAGE_BOUNDS_FORWARD =
  'app/products/SHIFT_PAGINATION_PAGE_BOUNDS_FORWARD';
export const SHIFT_PAGINATION_PAGE_BOUNDS_BACK =
  'app/products/SHIFT_PAGINATION_PAGE_BOUNDS_BACK';
