export const UPDATE_PRODUCTS_FILTER_FIELD =
  'app/products/UPDATE_PRODUCTS_FILTER_FIELD';
export const UPDATE_PRODUCTS_FILTER_CATEGORIES =
  'app/products/UPDATE_PRODUCTS_FILTER_CATEGORIES';
export const SET_INITIAL_STATE = 'app/products/SET_INITIAL_STATE';
